//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.235
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiatLux.Data.Local {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Chara {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chara() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiatLux.Data.Local.Chara", typeof(Chara).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alice.
        /// </summary>
        internal static string Alice {
            get {
                return ResourceManager.GetString("Alice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alice of Claire-Riviere.
        /// </summary>
        internal static string AliceLong {
            get {
                return ResourceManager.GetString("AliceLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bastel.
        /// </summary>
        internal static string Bastel {
            get {
                return ResourceManager.GetString("Bastel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bastel.
        /// </summary>
        internal static string BastelLong {
            get {
                return ResourceManager.GetString("BastelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boris.
        /// </summary>
        internal static string Boris {
            get {
                return ResourceManager.GetString("Boris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boris.
        /// </summary>
        internal static string BorisLong {
            get {
                return ResourceManager.GetString("BorisLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Doyen.
        /// </summary>
        internal static string Doyen {
            get {
                return ResourceManager.GetString("Doyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Doyen.
        /// </summary>
        internal static string DoyenLong {
            get {
                return ResourceManager.GetString("DoyenLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fortune.
        /// </summary>
        internal static string Fortune {
            get {
                return ResourceManager.GetString("Fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fortune.
        /// </summary>
        internal static string FortuneLong {
            get {
                return ResourceManager.GetString("FortuneLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juste.
        /// </summary>
        internal static string Juste {
            get {
                return ResourceManager.GetString("Juste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juste.
        /// </summary>
        internal static string JusteLong {
            get {
                return ResourceManager.GetString("JusteLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laetitia.
        /// </summary>
        internal static string Laetitia {
            get {
                return ResourceManager.GetString("Laetitia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laetitia Meles.
        /// </summary>
        internal static string LaetitiaLong {
            get {
                return ResourceManager.GetString("LaetitiaLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lazarett.
        /// </summary>
        internal static string Lazarett {
            get {
                return ResourceManager.GetString("Lazarett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lazarett.
        /// </summary>
        internal static string LazarettLong {
            get {
                return ResourceManager.GetString("LazarettLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lucien.
        /// </summary>
        internal static string Lucien {
            get {
                return ResourceManager.GetString("Lucien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lucien Clavant.
        /// </summary>
        internal static string LucienLong {
            get {
                return ResourceManager.GetString("LucienLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marion.
        /// </summary>
        internal static string Marion {
            get {
                return ResourceManager.GetString("Marion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marion Lefevbre.
        /// </summary>
        internal static string MarionLong {
            get {
                return ResourceManager.GetString("MarionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nathan.
        /// </summary>
        internal static string Nathan {
            get {
                return ResourceManager.GetString("Nathan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nathan Ismael.
        /// </summary>
        internal static string NathanLong {
            get {
                return ResourceManager.GetString("NathanLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ninon.
        /// </summary>
        internal static string Ninon {
            get {
                return ResourceManager.GetString("Ninon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ninon Atias.
        /// </summary>
        internal static string NinonLong {
            get {
                return ResourceManager.GetString("NinonLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sonia.
        /// </summary>
        internal static string Sonia {
            get {
                return ResourceManager.GetString("Sonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sonia Schoenblick.
        /// </summary>
        internal static string SoniaLong {
            get {
                return ResourceManager.GetString("SoniaLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vincent.
        /// </summary>
        internal static string Vincent {
            get {
                return ResourceManager.GetString("Vincent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vincent Albin.
        /// </summary>
        internal static string VincentLong {
            get {
                return ResourceManager.GetString("VincentLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xavier.
        /// </summary>
        internal static string Xavier {
            get {
                return ResourceManager.GetString("Xavier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xavier Fideo.
        /// </summary>
        internal static string XavierLong {
            get {
                return ResourceManager.GetString("XavierLong", resourceCulture);
            }
        }
    }
}
